import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Background from '../components/Background/Background'
import Hero from '../components/Hero/Hero'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  const [bgColor, setBgColor] = useState<'normal' | 'dark'>('normal')
  return (
    <div className={styles.container}>
      <Head>
        <title>Mendee.Digital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Background bgColor={bgColor}>
          <Hero bgColor={bgColor} />
        </Background>
      </main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  )
}

export default Home
